---
title: "B. Master's Thesis Plan"
author: "Nathalie Mayor"
output: 
  pdf_document:
header-includes:
    - \usepackage{setspace}\doublespacing
    - \usepackage{float}
bibliography: thesis.bib
link-citations: yes
linkcolor: blue
fontsize: 11pt
---
Word count: `r as.integer(sub("(\\d+).+$", "\\1", system(sprintf("wc -w %s", knitr::current_input()), intern = TRUE)))`

Percentage: `r as.integer(sub("(\\d+).+$", "\\1", system(sprintf("wc -w %s", knitr::current_input()), intern = TRUE)))/18000`

### 1. Introduction

A precise estimate of the covariance matrix is required in many applications. It is of primary importance in the determination of optimized weights in the context of the minimum variance portfolio (among other applications in finance) as it is the only parameter that needs to be estimated. The sample covariance which is the standard estimator has favorable asymptotic properties but appears to fail in the context of high dimensionality as it contains estimation errors that are harmful to the optimization. When the number of observations is smaller than the number of variables, the empirical estimate of the covariance matrix is singular and cannot be inverted. However, in the minimum variance portfolio problem, the inverse of the matrix is required in order to obtain the weights. In such a setting, alternative approaches have been proposed in the literature, including regularized estimators and I would like to focus my research on this category of estimators

In fact, it is, in practice and according to multiple scholars among which *...*, difficult to consistently outperform the naive diversification approach offered by the equally-weighted portfolio i.e. the $N$ assets have the weight $\frac 1N$. The naive diversification approach does not require any estimation and therefore is free from its resulting errors and depending on the rebalancing period, allows a relatively low turnover rate which enables lower transaction costs in practice. 


### 2. The Mean-Variance Framework

@markowitz1952portfolio introduced the Modern Portfolio Theory (MPT) which provides a mathematical formulation and solution to the portfolio choice and specifically, how should wealth be optimally allocated across all available assets. The Modern Portfolio theory also known as the mean-variance framework, is based on a simple normative criterion stipulating that investors must, or should, reason in terms of the expected mean and variance of the portfolio expected returns and construct a portfolio which most suitable for his needs, notably given his risk preferences. For a given level of average expected return, investors choose to minimize the variance, or conversely, for a given level of variance, to maximize the return. In other words, portfolio should be constructed, for a desired level of return, has the lowest variance or, for a given level of variance, allows the highest possible return to be expected. 

In this Chapter, we provide an overview of the Modern Portfolio Theory assumptions, the formulation of its optimization problem and introduce the model's sources of limitations.

### 2.1 Underlying Assumptions 

The framework developed in @markowitz1952portfolio requires the establishments of a number of assumptions.  These assumptions concern investors preferences, market conditions the statistical properties of the asset returns. Regarding investors' preferences, it is assumed that all investors prefer high returns with respect to low returns, all else being the equal e.g. given two similar asset carrying the same risk (measured by their variance), an investor is expected to choose the asset with the highest rate of return. This directly refers to the key assumptions of consumer choice theory and the principle that preferences exhibit non-satiation. In the context of the risk preferences, it is assumed that investors are Risk-averse and their choice only based on expected return and variance ($\mu-\sigma$ principle). This implies that their preferences can be represented by concave utility functions. Intuitively, this signifies that they prefer stable returns over uncertain ones, ceteris paribus. This signifies that investors will, in our setting, choose to minimize the risk, equivalently, the variance of their investments for a desired level of expected returns (measured as the mean portfolio return) , *it is additionally assumed that they do this optimization over just one period which is the same for all investors*. It is further assumed that that investors are rational and identical agents. Concerning market conditions, it is assumed that markets are perfect. This implies that the market is frictionless and perfectly liquid. All relevant information to the asset prices is freely and easily accessible, among all investors who update their portfolio immediately and without any transaction costs. Because of the liquidity, trades of any size can be made. Additionally, investors take the asset prices as given: they are price takers and have no ability to influence asset prices (perfect competition) which are exogenous. It is also considered that investors can take on short-selling positions on assets, in practice, this means that investors can borrow an asset from a broker and sell it. A short position on asset $i$ is mathematically represented by a negative weight $w_i$ in the portfolio. Investors can also borrow and lend unlimitedly at the same risk-free rate and without risk. Finally, it is also assumed that investors invest the totality of their wealth, i.e. there is no savings. Regarding statistical properties of asset returns, it is assumed that asset returns are stationary, meaning that a given asset returns' mean, variance, autocorrelation structure and more generally its unconditional joint probability distribution are not time dependent. While specifically, the mean-variance optimization requires that returns have finite mean and variance and that investors make their decisions solely based on these two measures, common formulations of the Modern Portfolio Theory require either that returns follow a multivariate normal distribution or that investors preferences can be represented by a quadratic utility function. Assuming that returns are multivariate normally distributed is quite a strong assumption. The mean variance framework requires the returns to be fully described by their mean, variance and covariance. While the multivariate normal distribution has this feature, additionally distributions satisfy this criteria e.g. the t-student distribution or the class of elliptical distributions. Although effectively questionable, the multivariate normal distribution has some advantages in practice. The distinct covariance estimators that we will study in this thesis assume various distributions for the asset returns an we will discuss each of these choices in more details *in the dedicated Chapter*. Additionally, the described assumptions refer to the classical mean-variance framework and few of them will be relaxed in the continuation of the thesis as we will focus on a particular portfolio optimization case; the Global Minimum Variance Portfolio that demands less restrictive requirements.


### 2.2 Theoretical Fundations

Diversification in the context of portfolio choice is a fundamental concept to the the Modern Portfolio Theory that we need to introduce before formalizing the portfolio optimization problem. 

(The variance should be understood as a measure of the degree of dispersion of the variable (the asset returns in this case) around its mean value. Thus, the higher the variance, the greater the dispersion of an asset's return around its mean. This statistic can thus be assimilated to an objective measure of risk. From a financial point of view, we have a greater probability of obtaining an actual return that is far from the expected return for an asset whose return variance is high.)

The total risk or volatility of an individual asset is two-fold. We speak of idiosyncratic risk (also called specific or unsystematic risk) as the risk particular to each financial asset and of systematic risk for the risk inherent to the entire market or the sector in which we want to invest. On the portfolio level, considering a universe of assets, correlations between each pairs of assets are an important factor to take into account when allocating a portfolio.  By combining various assets (and also asset classes) together, portfolio diversification allows to eliminate the idiosyncratic component of each financial asset thus, reducing the overall portfolio variance. More precisely, the portfolio variance can be reduced by combining assets that are only *weakly* correlated and also mixing *many* assets. Indeed, the variance of the portfolio returns is given by \ref{eq:1}[^1]: 

\begin{align} \label{eq:1}
\operatorname{Var}\left(R_{p}\right)=\sum_{i=1}^{n} w_{i}^{2} \sigma_{i i}+\sum_{i=1}^{n} \sum_{j=1, j \neq i}^{n} w_{i} w_{j}       \rho_{ij}\sigma_i\sigma_j=w^{\top} \Sigma w
\end{align}


[^1]: Adapted from Prof. Paul Söderlind, F 2020, 7,315: Theory of Finance , *Lecture Notes in Finance 1*, Chapter 2, University of St.Gallen.

Where $w_i$ is the portfolio weight on asset $i$, $\sigma_{ii}$ is the variance of asset $i$ ($\sigma_{i}$ is the standard deviation of asset $i$) and $\rho_{ij}$ is the correlation between asset $i$ and asset $j$.  Moreover $\sigma_{ij}=\rho_{ij}\sigma_i\sigma_j$ is the covariance of assets $i$ and $j$ and $\Sigma$ defines the covariance matrix. 

\ref{eq:1} shows that the overall portfolio variance positively depends on the correlation between the assets that compose the portfolio. Clearly, if asset returns were perfectly (positively) correlated $(\rho=1)$, the diversification effect would be null sinc this scenario offers no protection with respect to a single uncertain asset. consequently, it  would not contribute to the reduction of risk. Thus when assets are weakly correlated or, even better, negatively correlated, the diversification effect can be enhanced and the portfolio variance reduced. Generally, the correlation across asset returns is larger for securities belonging to the same or related industries, thus the more different industries are included in the stock universe, the greater the diversification benefits. Additionally to the level of correlation, the diversification effect also depends on the number of assets considered. E.g. considering the simple case of an equally weighted portfolio with $n$ assets, we have that $w_i = \frac 1n$,  $\forall i$ and the variance of the portfolio is :

\begin{align} \label{eq:2}
\operatorname{Var}\left(R_{p}\right)=\frac{1}{n}\left(\bar{\sigma}_{i i}-\bar{\sigma}_{i j}\right)+\bar{\sigma}_{i j}
\end{align}

Where $\bar{\sigma}_{ij}$ is the average covariance of two returns and in the limit, we have that $\displaystyle\lim_{n \to \infty} Var(R_p)=\bar{\sigma}_{ij}$ : only the average covariance, the non-diversifiable risk, matters. Of course, it is assumed that  $\bar{\sigma}_{ii}$ is positive which is realistic. Intuitively, it is infeasible to construct a basket of random variables that are on average negatively correlated with each other. Moreover, it can be shown that in the limit, $\bar{\sigma}_{ij}$ must be non-negative since the average correlation's low bound can be expressed as as follows: $-\frac{1}{n-1} \leq \bar{\rho}_{ij}$, *please see the proof in the Appendix*.

As a matter of fact and similarly to most economic variables, asset returns tend to move together, they are, for the most part, positively correlated. Although few individual asset prices and industries have historically moved in opposite direction of the economic activity, the expansions and contractions economy spread and pass on to the general behavior of asset returns as a whole. 

For a given stock universe, the mean-variance frontier (MVF) is formed by the portfolios whose allocations (combination of assets) minimize the variance for a given expected return. Depending on the point of view. It can equivalently be defined as the set of portfolios that maximize the expected returns for a given level of risk that the investor is willing to accept. Thus, the mean-variance frontier represents an ensemble of efficient portfolios i.e. there exist no portfolio that can achieve a lower portfolio volatility for a fixed level of expected return.  With the portfolio expected return ($ER_p$) and variance ($Var(R_p)$) expressed as

\begin{align} \label{eq:3}
\begin{split}
E R_p & = w^\top \mu \\
Var(R_p) & = w^\top \Sigma w 
\end{split}
\end{align}

With $\mu$, the $n \times 1$ of average returns of the $n$ assets considered for the portfolio allocation, $\Sigma$ the $n\times n$ returns covariance matrix and $w$, the $n \times 1$ vector of portfolio weights. 

Based on these definitions, the formulation of the Modern Portfolio Theory optimization problem was defined in multiple manners. Here we present a formulation which frames the portfolio optimization problem as follows: the selection of portfolio weights that minimize the portfolio risk subject to a target level of expected returns that the portfolio is required to achieve. The optimization is also subject to the constraint that all (normalized) portfolio weights must sum to one, since, as mentioned in the assumption, the investor allocate all of his wealth.

The mean-variance optimization problem seeking to minimize the level of portfolio risk for a given target return $\mu^*$ can be presented as follows:

\begin{align} \label{eq:4}
\begin{split}
w_{MV} =&\arg \min_{w_i}\:  Var(R_p) \text{ subject to } \\
E&[R_p]=\mu^* \text{ and } w^\top 1_n=1
\end{split}
\end{align}

Based on \ref{eq:3} and \ref{eq:4}, the problem can be expressed trough the Lagrangian: $\mathcal{L}(w,\lambda)=w^\top\Sigma w -\lambda(\mu^* - w^\top\mu -R_f )$. Solving the the first order conditions for $w$, we obtain the lagrange parameter: $\lambda_*=\frac{2\mu\Sigma w}{\mu^\top\mu}$. Replacing this result into the Lagrangian allows us to obtain a solution for the (normalized) vector of portfolio weights $w$, i.e. the allocation that minimize the portfolio risk through minimizing its variance through[^2]:

\begin{align} \label{eq:5}
w = \frac{\mu^*-R_f}{(\mu^e)^\top\Sigma^{-1}\mu^e}\Sigma^{-1}\mu^e
\end{align}

[^2]: Prof. Paul Söderlind, F 2020, 7,315: Theory of Finance , *Lecture Notes in Finance 1*, Chapter 3, University of St.Gallen.

Considering a universe of $n$ risky assets for a given target expected return $\mu^*$, $1_n$, a 1-vector of size $n$, $R_f$, the risk free rate and $\mu^e$, the vector of mean excess returns ($n\times 1$). Using \Ref{eq:4} allows to compute the efficient frontier for each level of expected return $\mu^*$.

\ref{eq:4} allows us to build the mean-variance frontier as the curve connecting all resulting efficient portfolios as for any level of target expected return $\mu^*$ it gives the weights to form the corresponding least volatile portfolio. It stands out from \ref{eq:5} that in order to obtain the optimal portfolio weights for a chosen $\mu^*$, it is required to estimate the asset expected returns, the asset covariance matrix and inverse [^3] it. Both the asset returns covariance matrix and the real expected asset returns are challenging components to estimate. Usually, classical sample estimators carry significant estimation errors that can easily offset the diversification benefits enabled through the portfolio optimization, this phenomenon will be discussed further in [a dedicated section](#related-issues-and-improvement-directions).

[^3]: some estimation approaches that we will study directly estimates the inverse covariance matrix of the asset returns.

Considering the set of optimal portfolios, the Global Minimum Variance Portfolio[^4] represents the efficient portfolio of risky assets carrying the least risk. The optimization problem can be expressed as[^6]:

[^4]: An other important result from the MPT is the tangency portfolio which is the point on the Mean-variance frontier and the risk free asset are tangent. Its weights are given by $w_{T}=\frac{\Sigma^{-1}\mu^e}{1_n^\top \Sigma^{-1}\mu^e}$ and the particularity of this portfolio is that it is the most efficient portfolio from a risk-reward ratio perspective as it has the highest possible Sharpe ratio of all mean-variance portfolios. It is possible to construct any portfolio  that optimally combine risk and return for a given risk tolerance as a mix of the tangency portfolio and cash (or risk free rate). Although the tangency portfolio's important implications, we will not detail it further in this thesis as the global minimum variance portfolio allows us to isolate and study the covariance matrix of asset returns with more precision (since the expected asset returns need to me estimated in order to obtain a solution for the tangency portfolio weights $w_T$).   

\begin{align} \label{eq:6}
\begin{split}
w_{GMV}=\arg \min_{w_i}\: &Var(R_p) \text{ subject to }\\
w^\top 1_n&=1
\end{split}
\end{align}

[^6]: Adapted from Prof. Paul Söderlind, F 2020, 7,315: Theory of Finance , *Lecture Notes in Finance 1*, Chapter 3, University of St.Gallen.

and the corresponding optimal weights are defined by the following formula:

\begin{align} \label{eq:7}
w_{GMV}= \frac{\Sigma^{-1}1_n}{1_n^\top\Sigma^{-1}1_n}
\end{align}



As we can see from \ref{eq:4} and \ref{eq:5}, the asset covariance matrix, or more precisely, its inverse plays a crucial role in the mean-variance portfolio optimization. In fact the global minimum variance portfolio's weights formulation \ref{eq:5} is extremely convenient since it *only* requires us to estimate the (inverse) covariance matrix of asset returns whereas the computation of any other optimal portfolio weights (\ref{eq:4}) additionally requires the estimation of the real expected returns. Thus, the estimated weights of the global minimum variance portfolio are free from errors resulting from the estimation of asset returns as it could be the case for the estimation of the weights of any other mean-variance optimal portfolios as defined by \ref{eq:4}. 


#### 2.2.1 On Risk Based Portfolios 

*BLACK LITTERMAN*

The Global Minimum Variance Portfolio falls within the framework of risk based allocation methods. These approaches

such as the risk budgeting which aims to allocate risk across the assets and risk parity consisting in distributing an equal amount of risk across the assets approaches that similarly focus on asset volatility and avoid the difficult task of estimation expected asset returns and the resulting estimation errors.

The minimum-variance strategy that we study as part of the mean-variance portfolio selection is an optimization based approach, that, as discussed focus on risk. In the financial literature, various different methods that are also based solely on risk were developed. Among those, we can cite the risk budgeting and risk parity approaches. The tactical asset allocation developed by BLACK LITTERMAN (1992) and the dynamic optimization proposed by MERTON (1971) both rely on optimization whereas Risk based asset allocation focus on risk and diversification, no estimation of expected asset returns. Risk parity (Allen 2010, Foresti and rush 2010)

Most Diversified Portfolio Choueifaty and Coignard [2008]
Risk contribution portfolio Allen [2010], Foresti and Rush [2010], Levell [2010], and Maillard, Roncalli, and Teiletche [2010]


The only input required to determine the portfolio composition is a model of risk.

In this thesis, we focus on the estimation of the covariance matrix of asset returns and the reduction of its estimation errors. Hence, we choose to concentrate on the case of the Global Minimum Variance Portfolio as described by \ref{eq:5}, aiming to provide the portfolio carrying the least risk. Since this portfolio allocation strategy only requires the estimation of the covariance matrix, it allows to isolate its estimation errors from the errors arising from the estimation of the real expected returns. 

Clearly, the obtained portfolio weights resulting from the mean variance optimization are highly sensitive on the estimated covariance matrix of asset returns. Usually, resulting in a high turnover of the portfolio and extreme weights.  

### 3. The Covariance and Precision Matrices

#### Theoretical Framework

#### The Standard Approach

#### Related Issues and Improvement Directions

Thus, although the Modern Portfolio Theory is relatively simple to understand and intuitive, its methods arouse lively debates in the literature. Criticisms were motivated by some of the framework's assumptions, considered as unrealistic.

@rice2006mathematical (p.138) defines covariance as the the joint measure of the variability of two random variables. It captures, in finance, the interaction between two assets i.e. their fluctuation relative to one another.  

 

- problems in modelling and estimation of high dimensional data
- covariance matrix in finance used to find optimal asset allocation, manage risk or price derivatives
- In this thesis we focus on covariance estimation but in financial applications the end goal is not the estimation in itself but rather e.g. to find the optimal portfolio selection. The estimation of the covariance matrix allows to find the optimal portfolio weights for the portfolio allocation depending on the investor's goal (global minimum variance portfolio, tangency portfolio).
- The standard approach consists in plugging selected covariance estimator in the formula which determines the optimal weights.
- The sample covariance matrix is asymptotically efficient under classical asymptotically statistical theory, i.e. when the sample size goes to infinity and the number of variable is fixed, the standard sample covariance matrix converges to the true covariance matrix. However, the properties of the sample estimator are limited for practical applications in finance. When $n>N$ the sample covariance matrix is ill-conditioned and singular, thus, it cannot be inverted.
- 1st Limitation of the sample cov: we assume non-stationary data, the parameters and distributions (covariance) are not constant overtime. this means that the sample estimator is not consistent
- 2nd limitation of the sample cov: 
- estimate de covariance of data from the last 2 years (504 days) as any data prior that does not reflect the current market situation. 
- here: the population size and the sample size are of the same order
- **Stein** (@stein1956some, @stein1975estimation) introduces shrinkage estimators, gold standard (according to @ledoit2015spectrum) and hard to beat empirically. however requires normality, does not guarantee a semi-positive definite matrix: not invertible, only defined when the sample size > dimension, the concept has been used in @dey1985estimation, @haff1980empirical, @ledoit2004well and @won2013condition


### 4. Literature Review: Estimating the Covariance/ Precision Matrices

OVERALL Proposed Estimators for the Covariance Matrix

#### FROM THE PROPOSAL
- **@james1992estimation** introduce the shrinkage estimator as a trade-off between estimation and specification errors. They show that the Stein's estimator that shrinks the values towards the average leads to smaller total squared error than the maximum likelihood estimator.

- **@bengtsson2002portfolio** use Bayesian shrinkage and PCA in combination with random matrix theory. They shrink the sample covariance matrix towards a single principal component covariance matrix.

- Olivier Ledoit and Michael Wolf have substantively contributed to the literature with their popular shrinkage estimators. In their papers, they propose an alternative loss function that does not involve the inverse matrix. Indeed, covariance matrix shrinkage estimators whose quadratic loss is based on the inverse covariance matrix tend to fail in high dimensionality. More specifically:

  - **@ledoit2003improved** suggest a shrinkage method that consists in taking a weighted average of the sample covariance matrix and a single-index model estimator (covariance matrix implied by the market model of **@sharpe1963simplified**). They control the imposed structure through the weight assigned to the single index model estimator. Their findings show that a combination gives better results than the estimators considered on their own and other traditional estimators.

  - **@ledoit2004honey** show that a combination of the sample covariance matrix with the constant-correlation model estimator leads to improved results.

  - **@ledoit2004well** Introduce a well conditioned and distribution free estimator that shrinks the sample covariance matrix towards the identity matrix.

- **@jagannathan2003risk** show that an equally weighted average of the sample covariance matrix and a single-index model estimator performs similarly than the more complex estimator suggested by Ledoit and Wolf.

- **@disatnik2007shrinking** compared multiple shrinkage estimators based on the ex-post standard deviation of the global minimum variance portfolio. They evaluate the following methods: **@ledoit2003improved**, **@ledoit2004honey**, **@jagannathan2003risk**, **@bengtsson2002portfolio**, a portfolio of the sample matrix, the single-index matrix and the constant correlation
matrix that they introduce, a portfolio of the sample matrix, the single-index matrix, the constant correlation matrix
and the diagonal matrix that they introduce. They fail to conclude that any of these methods is better than another, and show that there is no statistically significant gains from using sophisticated shrinkage estimators compared to simpler estimators. 

- **@sancetta2008sample** extended the shrinkage approach of @ledoit2003improved to autocorrelated data.

- **@friedman2008sparse**[^100] introduce the graphical LASSO for the estimation of the inverse covariance matrix.

- **@witten2009covariance**$^100$ study the ridge, lasso and elastic-net methods for the estimation of the inverse covariance matrix in a high dimensional setting. They show that these methods fall into the covariance-regularized regression framework.

- **@van2016ridge**$^100$ analyze the rigde estimation of the inverse covariance matrix in a high dimensional context. They compare **@friedman2008sparse**'s graphical lasso and conclude that the ridge method leads to better results.

[^100]: **@friedman2008sparse**, **@witten2009covariance** and **@van2016ridge** differ from the previous methods because they directly estimate the inverse covariance matrix (precision matrix) instead of the covariance matrix.

- **@6935094** propose a multi-target shrinkage estimator for the covariance matrix that is based on **@ledoit2003improved**'s
method and use several targets simultaneously. This approach appeared to increase the flexibility of the estimator and lower the MSE.


#### 3.1 Shrinkage Estimators for the Covariance Matrix

##### 3.1.1 Shrinkage Estimators for the Covariance Matrix of Asset Returns

(Major contributions to the covariance matrix estimation and more details on shrinkage approaches)

### 5. Conceptual/Theoretical Framework - Estimation of the Covariance Matrix - Overview of the Solutions

(theoretical framework)

(financial theory, mean-variance optimization and estimation problems regarding the covariance matrix)

- problems in modelling and estimation of high dimensional data
- covariance matrix in finance used to find optimal asset allocation, manage risk or price derivatives
- In this thesis we focus on covariance estimation but in financial applications the end goal is not the estimation in itself but rather e.g. to find the optimal portfolio selection. The estimation of the covariance matrix allows to find the optimal portfolio weights for the portfolio allocation depending on the investor's goal (global minimum variance portfolio, tangency portfolio).
- The standard approach consists in plugging selected covariance estimator in the formula which determines the optimal weights.
- The sample covariance matrix is asymptotically efficient under classical asymptotically statistical theory, i.e. when the sample size goes to infinity and the number of variable is fixed.

### (Analysis of the estimators)

(simulated data, shrinkage parameters)

### 6. Methodology

(data description, windows, sampling, simulated data)

### 7. Analysis - Out-of-Sample Evaluation of Competing Approaches

(application to several portfolios, analysis of the portfolios volatility and additional measures)

### 8. Conclusion

- Table of Contents
- List of Figures, Illustrations and Tables 
- Bibliography 
- Appendix 



\newpage 

# References













































